owner: el-thangmai
repo: status

sites:
  - name: Cleeksy Platform
    url: https://api.cleeksy.com/ready
    expectedStatusCodes:
      - 200
      - 403

status-website:
  cname: ajyqfiyyqr.cleeksy.com
  logoUrl: https://app.cleeksy.com/assets/images/favicon.svg
  name: Cleeksy
  navbar:
    - title: Status
      href: /
    - title: Homepage
      href: https://cleeksy.com